using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Text.Json.Nodes;

namespace BingusSpeak
{
    public class Dialog
    {
        /* Just a serializiation of the dialog and dialoginfo thingies. We will be iterating through them a lot so may as well do it. */
        public class DialogRecord
        {
            public enum Type
            {
                Greeting, Topic, Journal, Choice,
                Alarm, Attack, Flee, Hello, Hit, Idle, Intruder, Thief,
                AdmireFail, AdmireSuccess, BribeFail, BribeSuccess, InfoRefusal, InfoFail, IntimidateFail, IntimidateSuccess, ServiceRefusal, TauntFail, TauntSuccess
            }

            public readonly Type type;
            public readonly string id;

            public readonly List<DialogInfoRecord> infos;

            public DialogRecord(Type type, string id)
            {
                this.type = type;
                this.id = id.StartsWith("Greeting") ? "Greeting" : id; // change 'Greeting #' to just 'Greeting' for sanity reasons

                infos = new();
            }
        }

        public class DialogInfoRecord
        {
            private static int NEXT_ID = 0;

            public readonly int id; // generated id used when lookin up wems, not used by elden ring or morrowind
            public readonly Int128 trueId; // morrowind 64 bit int id
            public readonly DialogRecord.Type type;

            // static requirements for a dialog to be added
            public readonly string speaker, job, faction, cell;
            public readonly int rank;
            public readonly CharacterContent.Race race;
            public readonly CharacterContent.Sex sex;

            // non-static requirements
            public readonly string playerFaction;
            public readonly int disposition, playerRank;

            public readonly List<DialogFilter> filters;

            public readonly string text; // actual dialog text
            public string replacement;   // changes made by our app, null if unchanged
            public readonly string mp3;  // path to mp3 file of dialog line (if it exists, only some specific types of lines have them)

            public readonly string script; // result calls


            public readonly List<CharacterContent> used;  // list of characters that use this line
            public readonly bool split; // only marked true if this line was generated by the Split() functions

            /* Next couple of vars are generated in a second pass, these relate to how dialog lines unlock topics */
            public readonly List<DialogRecord> unlocks; // list of topics this line unlocks, if any

            public DialogInfoRecord(DialogRecord.Type type, JsonNode json)
            {
                id = DialogInfoRecord.NEXT_ID+=10;  // increment by 10 so we can use the 9 values between each id as the split text ids (guh)
                trueId = Int128.Parse(json["id"].GetValue<string>());
                this.type = type;

                string NullEmpty(string s) { return s.Trim() == "" ? null : s; }

                speaker = NullEmpty(json["speaker_id"].ToString());
                string raceStr = NullEmpty(json["speaker_race"].ToString());
                race = raceStr != null ? Enum.Parse<CharacterContent.Race>(raceStr.Replace(" ", "")) : CharacterContent.Race.Any;
                job = NullEmpty(json["speaker_class"].ToString());
                faction = NullEmpty(json["speaker_faction"].ToString());
                cell = NullEmpty(json["speaker_cell"].ToString());
                rank = int.Parse(json["data"]["speaker_rank"].ToString());
                Enum.TryParse(json["data"]["speaker_sex"].ToString(), out sex);

                playerFaction = NullEmpty(json["player_faction"].ToString());
                disposition = int.Parse(json["data"]["disposition"].ToString());
                playerRank = playerFaction!=null?int.Parse(json["data"]["player_rank"].ToString()):-1;  // minor MW bug fix. some dialogs have a mistake where they have a required rank set but no faction

                filters = new();
                foreach (JsonNode filterNode in json["filters"].AsArray())
                {
                    filters.Add(new(filterNode));
                }

                text = json["text"].ToString();
                replacement = null;
                mp3 = NullEmpty(json["sound_path"].ToString());

                script = json["script_text"].ToString();

                unlocks = new();
                used = new();

                split = false;
            }

            /* Constructor for creating splits */
            public DialogInfoRecord
            (
                Int128 trueId,
                DialogRecord.Type type,
                string speaker,
                string job,
                string faction,
                string cell,
                int rank,
                CharacterContent.Race race,
                CharacterContent.Sex sex,
                string playerFaction,
                int disposition,
                int playerRank,
                List<DialogFilter> filters,
                string text,
                string mp3,
                string script
            )
            {
                this.id = DialogInfoRecord.NEXT_ID += 10;
                this.trueId = trueId;
                this.type = type;
                this.speaker = speaker;
                this.job = job;
                this.faction = faction;
                this.cell = cell;
                this.rank = rank;
                this.race = race;
                this.sex = sex;
                this.playerFaction = playerFaction;
                this.disposition = disposition;
                this.playerRank = playerRank;

                this.filters = filters;

                this.text = text;
                replacement = null;
                this.mp3 = mp3;
                this.script = script;

                used = new();

                split = true;
            }

            public DialogInfoRecord Split(ESM esm, CharacterContent content)
            {
                string cellName = content.cell.name != null ? content.cell.name : "nowhere";  // %cell is literally unused in base game so whatever man lol
                FactionInfo factionInfo = esm.GetFaction(content.faction);
                string rankName = factionInfo != null ? factionInfo.GetRankName(content.rank) : "unaffiliated";

                string newText = text
                    .Replace("%name", content.name, StringComparison.OrdinalIgnoreCase)
                    .Replace("%class", content.job, StringComparison.OrdinalIgnoreCase)
                    .Replace("%race", content.race.ToString(), StringComparison.OrdinalIgnoreCase)
                    .Replace("%cell", cellName, StringComparison.OrdinalIgnoreCase)
                    .Replace("%faction", content.faction, StringComparison.OrdinalIgnoreCase)
                    .Replace("%rank", rankName, StringComparison.OrdinalIgnoreCase);

                DialogInfoRecord info = new(trueId, type, content.id, job, faction, cell, rank, race, sex, playerFaction, disposition, playerRank, filters, text, mp3, script);
                info.replacement = newText;
                info.used.Add(content);
                return info;
            }

            /* Returns replacement text if exists, otherwise the original unmodified text. */
            public string GetText()
            {
                return replacement != null ? replacement : text;
            }

            /* Returns true if has a dialog variable like %PcName or %Rank */
            public bool HasVariable()
            {
                return text.Contains("%");
            }

            /* Checks for a specific variable instead of just any */
            public enum Variable { Class, Name, PcClass, PcCrimeLevel, PcName, PcRace, Race, Cell, Faction, NextPcRank, PcRank, Rank }
            public bool HasVariable(Variable variable)
            {
                return text.ToLower().Contains($"%{variable}".ToLower());
            }


            /* Returns true if the original line has a dialog variable and there is no replacementText set, or if the replacementText still has one */
            public bool ReplacementHasVariable()
            {
                return (replacement == null && HasVariable()) || (replacement != null && replacement.Contains("%"));
            }

            /* Returns true if there is replacement text for this line */
            public bool HasReplacement()
            {
                return replacement != null && replacement != text;
            }

            public bool IsUnreachableFor(CharacterContent npc)
            {
                if (speaker != null && speaker != npc.id) { return true; }
                if (race != CharacterContent.Race.Any && race != npc.race) { return true; }
                if (job != null && job != npc.job) { return true; }
                if (faction != null && faction != npc.faction) { return true; }
                if (rank > npc.rank || (rank >= 0 && npc.faction == null)) { return true; }  // unsure if this is correct, i *think* it is but haven't verified
                if ((cell != null && npc.cell.name == null) || (cell != null && npc.cell.name != null && !npc.cell.name.ToLower().StartsWith(cell.ToLower()))) { return true; }
                if (sex != CharacterContent.Sex.Any && sex != npc.sex) { return true; }

                foreach (DialogFilter filter in filters)
                {
                    switch (filter.type)
                    {
                        case DialogFilter.Type.Function:
                            switch (filter.function)
                            {
                                case DialogFilter.Function.FactionRankDifference:
                                    {
                                        if (npc.faction == null) { return true; } break;
                                    }
                                case DialogFilter.Function.RankRequirement:
                                    {
                                        if (npc.faction == null) { return true; }
                                        break;
                                    }
                                case DialogFilter.Function.SameFaction:
                                    {
                                        if (npc.faction == null) { return true; }
                                        break;
                                    }
                                case DialogFilter.Function.PcExpelled:
                                    {
                                        if (npc.faction == null) { return true; }
                                        break;
                                    }
                                case DialogFilter.Function.Reputation:
                                    {
                                        if(!filter.ResolveOperator(npc.reputation)) { return true; }
                                        break;
                                    }
                                case DialogFilter.Function.Level:
                                    {
                                        if (!filter.ResolveOperator(npc.level)) { return true; }
                                        break;
                                    }
                                default: break;
                            }
                            break;

                        case DialogFilter.Type.NotCell:
                            switch (filter.function)
                            {
                                case DialogFilter.Function.NotCell:
                                    {
                                        // static check, characters in elden ring can't really travel around so it's fine for now. may need to change at some point tho
                                        if (npc.cell.name != null && npc.cell.name.ToLower().StartsWith(filter.id.ToLower())) { return true; }
                                        break;
                                    }

                                default: break;
                            }
                            break;

                        case DialogFilter.Type.NotId:
                            switch (filter.function)
                            {
                                case DialogFilter.Function.NotIdType:
                                    {
                                        if (npc.id == filter.id) { return true; }
                                        break;
                                    }

                                default: break;
                            }
                            break;

                        case DialogFilter.Type.NotClass:
                            switch (filter.function)
                            {
                                case DialogFilter.Function.NotClass:
                                    {
                                        if (npc.job == filter.id) { return true; }
                                        break;
                                    }

                                default: break;
                            }
                            break;

                        case DialogFilter.Type.NotRace:
                            switch (filter.function)
                            {
                                case DialogFilter.Function.NotRace:
                                    {
                                        if (npc.race.ToString().ToLower() == filter.id) { return true; }
                                        break;
                                    }

                                default: break;
                            }
                            break;

                        case DialogFilter.Type.NotFaction:
                            switch (filter.function)
                            {
                                case DialogFilter.Function.NotFaction:
                                    {
                                        // Checking speakers faction, static true/false is fine for this as well
                                        if (npc.faction == filter.id) { return true; }
                                        break;
                                    }

                                default: break;
                            }
                            break;

                        default: break;
                    }
                }
                return false;
            }
        }

        public class DialogFilter
        {
            public enum Type { NotLocal, Journal, Dead, Item, Function, NotId, Global, Local, NotFaction, NotCell, NotRace, NotClass }
            public enum Operator { Equal, NotEqual, GreaterEqual, LessEqual, Less, Greater }
            public enum Function
            {
                VariableCompare, JournalType, DeadType, ItemType, Choice, NotIdType, PcExpelled, NotFaction, SameFaction, RankRequirement,
                PcSex, SameRace, PcHealthPercent, PcHealth, PcReputation, NotCell, PcVampire, NotRace, PcSpeechcraft, PcLevel, NotClass, PcCrimeLevel,
                SameSex, PcMercantile, PcClothingModifier, FactionRankDifference, PcCorprus, PcPersonality, ShouldAttack, PcAgility, PcSneak, TalkedToPc,
                PcIntelligence, Alarmed, Global, Detected, Attacked, Level, PcBlightDisease, PcCommonDisease, PcBluntWeapon, Reputation, PcStrength,
                CreatureTarget, Weather, ReactionHigh, ReactionLow, HealthPercent, FriendHit
            }

            public readonly Type type;
            public readonly Function function;
            public readonly Operator op;
            public readonly string id;
            public readonly int value;

            public DialogFilter(JsonNode json)
            {
                Enum.TryParse(json["filter_type"].ToString(), out type);
                Enum.TryParse(json["function"].ToString(), out function);
                Enum.TryParse(json["comparison"].ToString(), out op);

                id = json["id"].ToString().ToLower();

                if (json["value"]["type"].ToString() == "Integer")
                {
                    value = int.Parse(json["value"]["data"].ToString());
                }
                else
                {
                    value = 0;
                }

            }

            /* Resolve the comparison value for 0=False / 1=True style filter conditions. EX: SameRace or SameFaction */
            public string ResolveBinaryComparison()
            {
                bool compare = value == 1;
                if (op == DialogFilter.Operator.NotEqual) { compare = !compare; }
                return compare ? "True" : "False";
            }

            /* Actually resolve a comparison operation from this filter with a given value */
            public bool ResolveOperator(int leftValue)
            {
                switch (op)
                {
                    case Operator.Equal: return leftValue == value;
                    case Operator.NotEqual: return leftValue != value;
                    case Operator.GreaterEqual: return leftValue >= value;
                    case Operator.Greater: return leftValue > value;
                    case Operator.LessEqual: return leftValue <= value;
                    case Operator.Less: return leftValue < value;
                    default: return false;
                }
            }

            /* Returns the esd version of the operator type as a string */
            public string OperatorString()
            {
                switch (op)
                {
                    case Operator.Equal: return "CompareType.Equal";
                    case Operator.NotEqual: return "CompareType.NotEqual";
                    case Operator.GreaterEqual: return "CompareType.GreaterOrEqual";
                    case Operator.Greater: return "CompareType.Greater";             // for the comparetype operators the mismatch only applys to the Less and LessOrEqual ops
                    case Operator.Less: return "CompareType.LessOrEqual";
                    case Operator.LessEqual: return "CompareType.Less";
                    default: throw new Exception("Invalid operator type! This should not happen!");
                }
            }

            /* same as above but symbol instead of string */
            public string OperatorSymbol()
            {
                switch (op)
                {
                    case Operator.Equal: return "==";
                    case Operator.NotEqual: return "!=";
                    case Operator.GreaterEqual: return ">";    // due to an issue with esd compiling >= and > are swapped. same issue with < and <= as well
                    case Operator.Greater: return ">=";
                    case Operator.LessEqual: return "<=";
                    case Operator.Less: return "<";
                    default: throw new Exception("Invalid operator type! This should not happen!");
                }
            }
        }
    }
}
